  Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/bionic64"

    config.vm.define "web" do |web|
      web.vm.provision "shell", path: "apache-install.sh"

      web.vm.provision "file", source: "apache-example.site",
        destination: "/tmp/configs/apache-example.site"

      web.vm.provision "shell", path: "apache-sites.sh"

    end

    config.vm.define "db" do |db|
      db.vm.provision "shell", path: "mysql-install.sh"
    end
  end