
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb| 
    vb.name = "test_vm" 
    vb.cpus = 2 
    vb.memory = "2048" 
  end 

  ### Configurations for virtualbox VM 
  config.vm.box = "ubuntu/focal64" 
  config.vm.network "private_network", ip: "192.168.56.100" 
  config.vm.hostname = "trungtin" 

end
